name: Auto Merge

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    if: false # This skips the entire job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auto-merge if success
      if: success()
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ######


