name: Auto-Merge to Dev

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is available
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Merge Main into Dev
        run: |
          git fetch origin dev
          git checkout dev
          git merge origin/main --no-ff -m "Auto-merge: main -> dev"
          git push origin dev
