name: Backup to GitHub

on:
  push:
    branches:
      - main  # Trigger on any push to the `main` branch
  pull_request:
    types: 
      - closed   # Trigger on PR merge (when PR is closed)
    branches:
      - main  # Ensure the PR is merged into `main`

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to backup repository
        run: |
          # Set up the backup remote
          git remote add backup https://github.com/Betrand1999/git-demo-backup.git
          
          # Push the main branch to the backup repo
          git push backup main

          # Push all tags to the backup repo
          git push --tags backup
