name: CICD
on:
 push:
   branches:
     - dev
     - main
jobs:
  build:
   runs-on: ubuntu-latest
   container:
      image: alpine
   steps:
     - name: actions/checkout 
       uses: actions/checkout@v2 
     - name: Coammnds
       run: |
        echo "Hello Worldd"
       