name: Check Merge

on:
  pull_request:
    branches:
      - main

jobs:
  validate-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev  # Ensure 'dev' branch is checked out
      - name: Run Checks on Dev
        run: |
          echo "Running checks on dev branch..."
          # Replace with tests, linters, etc.
          echo "All validations passed for dev!"
