name: Check Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  review-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Code Linting
        run: |
          echo "Running code linting checks..."
          # Replace with your linting tool, e.g., flake8, eslint, etc.
          echo "Linting successful."

      - name: Check for Required Approvals
        run: |
          echo "Checking for required approvals..."
          PR_APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews -q '.reviews | map(select(.state == "APPROVED")) | length')
          if [[ "$PR_APPROVALS" -eq 0 ]]; then
            echo "No approvals found. Failing the check."
            exit 1
          else
            echo "Pull request has been approved. Proceeding."
          fi
