name: Check Review

on:
  pull_request_review:
    types: [submitted]  # Trigger on review submission

jobs:
  review:
    if: github.event.review.state == 'approved'  # Only for approved reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Review
        run: echo "Reviewing code after approval..."
      - name: Code Quality
        run: |
          echo "Running code quality checks..."
          echo "Code quality check passed!"
